/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project_module.view;

import com.mycompany.project_module.controller.CUsuario;
import com.mycompany.project_module.module.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class VUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VUsuario.class.getName());

    /**
     * Creates new form VUsuario
     */
    public VUsuario() {
        initComponents();
    }
    
    public void limpiarPantalla(){
      TextId.setText("");
      TextNombre.setText("");
      TextApellido.setText("");
      TextTipoDeSangre.setText("");
      TextCargo.setText("");
      TextEmail.setText("");
      TextPassword.setText("");
    }
    
     public void cargarFormulario(){
        int fila = tablaUsuario.getSelectedRow();
        
        TextId.setText(tablaUsuario.getValueAt(fila , 0).toString());
        TextNombre.setText(tablaUsuario.getValueAt(fila , 1).toString());
        TextApellido.setText(tablaUsuario.getValueAt(fila , 2).toString());
        TextTipoDeSangre.setText(tablaUsuario.getValueAt(fila , 3).toString());
        TextCargo.setText(tablaUsuario.getValueAt(fila, 4).toString());
        TextEmail.setText(tablaUsuario.getValueAt(fila, 5).toString());
        TextPassword.setText(tablaUsuario.getValueAt(fila, 4).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        tipoDeSangre = new javax.swing.JLabel();
        cargo = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        TextNombre = new javax.swing.JTextField();
        TextApellido = new javax.swing.JTextField();
        TextTipoDeSangre = new javax.swing.JTextField();
        TextCargo = new javax.swing.JTextField();
        TextEmail = new javax.swing.JTextField();
        TextPassword = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        Resgistrar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        Limpiar = new javax.swing.JButton();
        actualizaTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        id.setText("id");

        nombre.setText("nombre");

        apellido.setText("apellido");

        tipoDeSangre.setText("tipo de sangre");

        cargo.setText("cargo");

        email.setText("email");

        password.setText("password");

        TextId.addActionListener(this::TextIdActionPerformed);

        TextPassword.addActionListener(this::TextPasswordActionPerformed);

        Consultar.setText("Consultar");
        Consultar.addActionListener(this::ConsultarActionPerformed);

        Resgistrar.setText("Registrar");
        Resgistrar.addActionListener(this::ResgistrarActionPerformed);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(this::EliminarActionPerformed);

        Modificar.setText("Modificar");
        Modificar.addActionListener(this::ModificarActionPerformed);

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuario);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(this::LimpiarActionPerformed);

        actualizaTabla.setText("Actualizar tabla");
        actualizaTabla.addActionListener(this::actualizaTablaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoDeSangre)
                    .addComponent(apellido)
                    .addComponent(password)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextId)
                            .addComponent(TextNombre)
                            .addComponent(TextApellido)
                            .addComponent(TextTipoDeSangre)
                            .addComponent(TextCargo)
                            .addComponent(TextEmail)
                            .addComponent(TextPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Resgistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(Modificar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actualizaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id)
                            .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre)
                            .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellido)
                            .addComponent(TextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoDeSangre)
                            .addComponent(TextTipoDeSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargo)
                            .addComponent(TextCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email)
                            .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password)
                            .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Consultar)
                            .addComponent(Modificar)
                            .addComponent(Resgistrar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(Limpiar)
                    .addComponent(actualizaTabla))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    private void TextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPasswordActionPerformed

    private void ResgistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResgistrarActionPerformed
 
        CUsuario controlEst = new CUsuario();
        String id = TextId.getText();
        if (!id.isEmpty()){
            JOptionPane.showMessageDialog(null, "en el registro no es necesario digitar el id");
            return;
        }
        String nombre = TextNombre.getText();
        String apellido = TextApellido.getText();
        String tipoDeSangre = TextTipoDeSangre.getText();
        String cargoText = TextCargo.getText();
        if(cargoText.isEmpty()){
           JOptionPane.showMessageDialog(null, "el cargo es obligatorio");
           return;
        }
        int cargo = Integer.parseInt(cargoText);
        
        if(!controlEst.existeCargo(cargo)){
            JOptionPane.showMessageDialog(null, "El cargo no existe");
            return;
        }
        String email = TextEmail.getText();
        String password = TextPassword.getText();
        
        Usuario user = new Usuario(0,nombre,apellido,tipoDeSangre,cargo,email,password);
          
        controlEst.registrarUsuario(user);
        limpiarPantalla();  
    }//GEN-LAST:event_ResgistrarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int id = Integer.parseInt(TextId.getText());
        CUsuario controlEst = new CUsuario();
        controlEst.eliminarUsuarios(id);
        limpiarPantalla();
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        CUsuario controlEst = new CUsuario();
        String idText =  TextId.getText();
        if(idText.isEmpty()){
            JOptionPane.showMessageDialog(null, "El id es necesario para la modificacion");
            return;
        }
        int id = Integer.parseInt(idText);
        String nombre = TextNombre.getText();
        String apellido = TextApellido.getText();
        String tipoDeSangre = TextTipoDeSangre.getText();

        int cargo = Integer.parseInt(TextCargo.getText());
        
        if(!controlEst.existeCargo(cargo)){
            JOptionPane.showMessageDialog(null, "El cargo no existe");
            return;
        }
        String email = TextEmail.getText();
        String password = TextPassword.getText();
        
        Usuario u = new Usuario(id,nombre,apellido,tipoDeSangre,cargo,email,password);
        controlEst.modificarUsuarios(u);
        controlEst.pintarTabla(tablaUsuario, controlEst.consultarEstudiante());
        limpiarPantalla();
    }//GEN-LAST:event_ModificarActionPerformed

    private void tablaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuarioMouseClicked
        cargarFormulario();
    }//GEN-LAST:event_tablaUsuarioMouseClicked

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        int id = Integer.parseInt(TextId.getText());
        CUsuario controlEst = new CUsuario();
        controlEst.pintarTabla(tablaUsuario, controlEst.consultarEstudiantePorId(id));
    }//GEN-LAST:event_ConsultarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CUsuario controlEst = new CUsuario();
        controlEst.pintarTabla(tablaUsuario, controlEst.consultarEstudiante());
    }//GEN-LAST:event_formWindowOpened

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        limpiarPantalla();
    }//GEN-LAST:event_LimpiarActionPerformed

    private void actualizaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaTablaActionPerformed
        CUsuario controlEst = new CUsuario();
        
        controlEst.pintarTabla(tablaUsuario, controlEst.consultarEstudiante());
    }//GEN-LAST:event_actualizaTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Resgistrar;
    private javax.swing.JTextField TextApellido;
    private javax.swing.JTextField TextCargo;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextPassword;
    private javax.swing.JTextField TextTipoDeSangre;
    private javax.swing.JButton actualizaTabla;
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel cargo;
    private javax.swing.JLabel email;
    private javax.swing.JLabel id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel password;
    private javax.swing.JTable tablaUsuario;
    private javax.swing.JLabel tipoDeSangre;
    // End of variables declaration//GEN-END:variables
}
